export const authBaseUrl = "https://auth-gq2.vwr.com/";
export const baseUrl = "https://api-vsr-stg4.vwr.com/";
export const client_id = "GSJtwsKH2BGo8WGQMIKndEH6OQRHFQDg";
export const apiKey = "6bkyk8Uifx3IAx01Zarvt4KcnGkzHEAG2P4Khgyn";
export const client_secret =
  "3T-zQ_R1IYalTEWnt7KpMBKJ8RjEo8MLoq-0pun_v58mFBAoEMcMJZ2gMOTvt1jQ";
export const app_version_check = "api/checkChannelVerison";
export const login = "oauth/token";
export const loginNew = "api/mobile/auth";
export const get_languages = "api/languages/";
export const get_account = "api/user/";
export const get_org = "api/user/organizations";
export const get_stockrooms = "api/user/organization/";
export const get_stockroom_detail = "api/stockroom";
// export const get_productList = "api/search/product";
export const get_productList = "api/stockroom/products";
export const user_privileges = "api/user/privileges";
export const get_productDetails = "api/stockroom/products/";
export const cost_centers = "/costCenters";
export const reasonCode = "api/stockroom/reasoncodes";
export const addReasonCode = "api/organization/reasoncodes";
export const set_push_notification_url = "api/pushNotification";
export const set_push_notification_logout_url = "api/pushNotification/logout";
export const get_notification_list = "api/user/notifications";
export const get_notification_count = "api/user/notificationsCount";
export const get_messages_list = "api/message";
export const get_messages_count = "api/message/count";
export const get_news_list = "api/news";
export const get_news_count = "api/news/count";
export const get_org_details = "api/organization";
export const getOrgLevelCurrency = "api/products/CurrencyId";
export const getReplenishProducts =
  "api/stock/replenish/products?sortBy=description:asc";
export const get_users_list = "api/stockroom/users";
export const replenish = "api/stock/replenish";
export const pi_count = "api/stockroom/piCounts";
export const get_pi_count_locations =
  "api/stockroom/locations?limit=0&offset=0&sortBy=locationName:desc";
export const replenishRequest = "api/stock/replenish/request";
export const replenishStockCorrect = "api/stock/stockcorrect";
export const addVwrProductSearch = "api/search/gw?";
export const addVwrStockRoomProducts = "api/stockroom/products";
export const get_stock_out = "api/stockroom/products/stockout";
export const get_stock_low = "api/stockroom/products/stocklow";
export const get_kpi_ProductList = "api/stockroom/products";
export const stock_correct = "api/stock/stockcorrect";
export const get_replenish_customerApprovalId =
  "api/stock/replenish/customerApprovalId";
export const get_spclhandlingmsg =
  "api/organization/stockrooms/spclhandlingmsg";
export const get_userEmailInfo = "api/userEmailInfo";
export const approvals = "api/approvals/";
export const consumeApprove = "api/approvals/consumeRequests/approve";
export const POUApprove = "api/approvals/pouOrders/approve";
export const consumeRequestsCount = "consumeRequests/count";
export const ordersCount = "orders/count";
export const pouOrdersCount = "pouOrders/pouCount";
export const consumeRequestsList = "api/stock/consume/requests";
export const ordersList = "orders";
export const pouOrdersList = "pouOrders";
export const getReceiveKPIs = "api/stockroom/orders/open/kpiCount";
export const receiveOrderList = "api/stockroom/orders/open";
export const receiveOrderDetails = "api/stockroom/orders/";
export const getReceiveList = "api/stockroom/orders/open/search/catalogs?";
export const setReceiveStock = "api/stockroom/orders/receive";
export const receiveValidate = "api/stockroom/orders/receive/validate";
export const setRejectStock = "api/stockroom/orders/reject";
export const get_terms_of_use = "api/terms";
export const set_license_agreed = "api/users/licenseAgreed";

//consume
export const departments = "departments";
export const consume = "api/stock/consume";
export const request_consume = "api/stock/consume/request";
export const consumeDetail = "api/stock/consume/requests/";
export const stockRoomLocations = "api/stockroom/locations";
export const users = "api/users/";
export const consumeApproval = "api/stock/consume/";
export const stockTransfer = "api/stockroom/products/move";
export const batchProducts = "batchProducts";
export const printBarcodeTemplate = "api/barcode/products/mobile/print";
export const refreshTokenUrl = "api/mobile/refreshToken";

